from __future__ import annotations

import getpass
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / ".env"
GITIGNORE_PATH = ROOT / ".gitignore"


def _run(cmd: list[str]) -> tuple[int, str]:
    p = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
    return p.returncode, (p.stdout + p.stderr).strip()


def ensure_gitignore_protection() -> None:
    required = [".env", ".env.*", "!.env.example"]
    existing = GITIGNORE_PATH.read_text(encoding="utf-8").splitlines() if GITIGNORE_PATH.exists() else []
    missing = [x for x in required if x not in existing]
    if missing:
        with GITIGNORE_PATH.open("a", encoding="utf-8") as f:
            if existing and existing[-1].strip() != "":
                f.write("\n")
            f.write("# Secrets\n")
            for line in missing:
                f.write(line + "\n")


def guard_and_unstage_env() -> None:
    """
    熔断保护：如果 .env 被加入暂存区，立刻取消暂存并中止。
    """
    code, out = _run(["git", "diff", "--cached", "--name-only"])
    if code != 0:
        return
    staged = {line.strip() for line in out.splitlines() if line.strip()}
    if ".env" in staged or any(x.startswith(".env") for x in staged):
        _run(["git", "restore", "--staged", ".env"])
        _run(["git", "reset", "HEAD", ".env"])
        raise RuntimeError("SECURITY FUSE: .env was staged. Staging has been cleared. Re-run after review.")


def prompt_secret(name: str, required: bool = False) -> str:
    while True:
        val = getpass.getpass(f"{name}{' (required)' if required else ' (optional)'}: ").strip()
        if val or not required:
            return val
        print(f"{name} is required.")


def main() -> int:
    print("=== SpreadSynth Credential Guide ===")
    print("输入凭据后将写入本地 .env（不会上传，.gitignore 已保护）")

    ensure_gitignore_protection()

    values = {
        # X API (OAuth1)
        "X_API_KEY": prompt_secret("X_API_KEY", required=False),
        "X_API_SECRET": prompt_secret("X_API_SECRET", required=False),
        "X_ACCESS_TOKEN": prompt_secret("X_ACCESS_TOKEN", required=False),
        "X_ACCESS_TOKEN_SECRET": prompt_secret("X_ACCESS_TOKEN_SECRET", required=False),
        # Optional X bearer
        "X_BEARER_TOKEN": prompt_secret("X_BEARER_TOKEN", required=False),
        # Community cookies
        "V2EX_COOKIE": prompt_secret("V2EX_COOKIE", required=False),
        "HN_COOKIE": prompt_secret("HN_COOKIE", required=False),
        # Optional GitHub token for star checks if needed
        "GH_TOKEN": prompt_secret("GH_TOKEN", required=False),
    }

    lines = [
        "# SpreadSynth local credentials",
        "# Auto-generated by ops/config_env.py",
        "# Never commit this file.",
        "",
    ]
    for k, v in values.items():
        safe = v.replace("\n", "").strip()
        lines.append(f'{k}="{safe}"')

    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Windows best effort: remove inherited read-only issues not needed; just verify
    print(f"\nSaved: {ENV_PATH}")
    ensure_gitignore_protection()

    try:
        guard_and_unstage_env()
    except RuntimeError as e:
        print(str(e))
        return 1

    print("Done. .env is local-only and protected by .gitignore.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
